# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: display.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rdisplay.proto\x1a\x1bgoogle/protobuf/empty.proto\"\"\n\x12\x44isplayTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t2G\n\x07\x44isplay\x12<\n\x0b\x44isplayText\x12\x13.DisplayTextRequest\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'display_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DISPLAYTEXTREQUEST']._serialized_start=46
  _globals['_DISPLAYTEXTREQUEST']._serialized_end=80
  _globals['_DISPLAY']._serialized_start=82
  _globals['_DISPLAY']._serialized_end=153
# @@protoc_insertion_point(module_scope)
